# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - gripper_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - base_link_link_1
      - link_1_link_2
      - link_2_link_3
      - link_3_link_4
    action_ns: follow_joint_trajectory
    default: true

  gripper_controller:
    type: FollowJointTrajectory
    joints:
      - link_4_right_gear_joint
    action_ns: follow_joint_trajectory
    default: false
