services:
  ros2-ai-waste-sorting:
    image: ros2-jazzy-waste-sorting:latest

    build:
      context: .
      dockerfile: Dockerfile

    container_name: waste-sorting

    command: sleep infinity

    network_mode: host
    ipc: host

    volumes:
      - ..:/home/ubuntu/ros2_ws/src
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /mnt/wslg:/mnt/wslg

    working_dir: /home/ubuntu/ros2_ws

    environment:
      - DISPLAY=${DISPLAY}
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - PULSE_SERVER=${PULSE_SERVER}
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_SOFTWARE=0
